version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - '9000:8000'
      - '9001:8001'
      - '9020:8020'
      - '9030:8030'
      - '9040:8040'
    environment:
      postgres_host: 172.17.0.1
      postgres_user: postgres
      postgres_pass: moneymoneyHOME888
      postgres_db: graphnode_moonbeam
      ipfs: '172.17.0.1:5001'
      ethereum: 'moonbeam:https://moonbeam.api.onfinality.io/public'
      RUST_LOG: info
      #  GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 'true'
      GRAPH_LOG: info
